export enum AuditAction {
  PROFILE_UPSERTED = 'PROFILE_UPSERTED',
  PROJECT_CREATED = 'PROJECT_CREATED',
  PROJECT_PUBLISHED = 'PROJECT_PUBLISHED',
  PROPOSAL_SUBMITTED = 'PROPOSAL_SUBMITTED',
  PROPOSAL_WITHDRAWN = 'PROPOSAL_WITHDRAWN',
  PROPOSAL_ACCEPTED = 'PROPOSAL_ACCEPTED',
  CONTRACT_CREATED = 'CONTRACT_CREATED',
}
